% BAR_SAR
%
% Search and replace terms in files using regular expressions.
%
% -------------
% DOCUMENTATION
% -------------
% Matlab REGEX documentation
%   https://ch.mathworks.com/help/matlab/ref/regexp.html
% Developing, debugging, & visualizing regexs online
%   https://regex101.com/
% Regex Tutorial & software
%   https://www.regular-expressions.info/
%
% -------------
% PERFORMANCE
% -------------
% Expected processing duration:
% 150.000 items to process at 2.000 items/minute = 80 min = 1h30
% Actual processing duration (MacBook Pro 2019, 8 cores, 16 GB RAM):
% 148.830 items to process = 5h = 500 items/minute
%
% -------------
% CREDITS
% -------------
% Vlad Atanasiu
% atanasiu@alum.mit.edu
% http://alum.mit.edu/www/atanasiu/
% 2021.10.05



% -----------------
% STEP 1: Manual replacement
% -----------------
% Before your run this program you may want to do a manual search and
% replace for those terms with multiple replacement possibilities, such as
% 'Eifall' > {'Einfall','Unfall'}.


% -----------------
% Define search and replace terms
% -----------------
% Other mappings, not yet applied: ...
sar = {...
    {'β','ß'},... % e.g.: daβ (beta > szett)
    {'Belegraphistin','Telegraphistin'},...
    {'Lelegraphistin','Telegraphistin'},...
    {'Belegraphist','Telegraphist'},...
    {'Lelegraphist','Telegraphist'},...
    {'ertrautung','Erkrankung'},...
    {'esterreich','Österreich'},...
    {'Anfall','Unfall'},...
    {'cominis','commis'},...
    {'Granz','Gränze'},...
    {'Granze','Gränze'},...
    {'Granzos','Gränze'},...
    {'hindenten','hindeuten'},...
    {'erbestimmten','unbestimmten'},...
    {'Feonz','Leonz'},...
    {'bereischer','bernischer'},...
    {'nvernager','Einvernahme'},...
    {'Erreifung','Erreichung'},...
    {'Pezialvertrages','Spezialvertrages'},...
    {'Zeuf','Genf'},...
    {'Luzerin scher','Luzernischer'},...
    {'Kithuung','Sitzung'},...
    {'Eisgenossenschaft','Eidgenossenschaft'},...
    {'Bodische','Badische'},...
    {'Junghi','Lunghi'},...
    {'Sthung','Sitzung'},...
    {'Oerr','Österr.'},...
    {'Rustzeug','Rüstzeug'},...
    {'Eucky','Buchy'},...
    {'Nüchtlinge','Flüchtlinge'},...
    {'stehtig','effektiv'},...
    {'Stuttwardt','Stuttgardt'},...
    {'Athung','Sitzung'},...
    {'anderial','material'},...
    {'Patis','Paris'},...
    {'Lochernitschein','Tschernitschoff'},...
    {'Otpreussen','Ostpreussen'},...
    {'Wandt','Waadt'},...
    {'Schulfold','Schulsold'},...
    {'Fr. Gallen','St. Gallen'},...
    {'Basellani','Baselland'},...
    {'Frachsel','Trachsel'},...
    {'Schung','Sitzung'},...
    {'Siehring','Sitzung'},...
    {'Montreue','Montreux'},...
    {'Deinzufolge','demzufolge'},...
    {'Schlagen','Splügen'},...
    {'Kronesendenz','Korrespondenz'},...
    {'Passe','Pässe'},...
    {'Tondrio','Sondrio'},...
    {'Ehenbahn','Eisenbahn'},...
    {'Sehung','Sitzung'},...
    {'Fardinien','Sardinien'},...
    {'Pardinien','Sardinien'},...
    {'Schwicherischen','Schweizerischen'},...
    {'hardinischen','sardinischen'},...
    {'Ministerims','Ministeriums'},...
    {'Sardimen','Sardinien'},...
    {'Rathegorie','Kathegorie'},...
    {'Blaufäure','Blausäure'},...
    {'Wegesche','Depesche'},...
    {'Pizung','Sizung'},...
    {'übermadt','übermacht'},...
    {'bhaus','Chaux'},...
    {'Pruntret','Pruntrut'},...
    {'Pruntent','Pruntrut'},...
    {'Brouct','Drouet'},...
    {'Rechtsent','Rechtsagent'},...
    {'Togasitgebühren','Transitgebühren'},...
    {'Departoments','Departements'},...
    {'Milln','Sitzung'},...
    {'Sezund','Sitzung'},...
    {'Moellesalaz','Moillesulaz'},...
    {'Württembern','Württemberg'},...
    {'gehändisch','Gesandtsch.'},...
    {'vorrespondiren','korrespondiren'},...
    {'Mendeisio','Mendrisio'},...
    {'Büttich','Lüttich'},...
    {'Maffen','Waffen'},...
    {'Marack','Waadt'},...
    {'Atzung','Sitzung'},...
    {'unker','unter'},...
    {'Kaatsch','Korratsch'},...
    {'Stoskanisches','Toskanisches'},...
    {'Odesse','Odessa'},...
    {'Fabriel','Gabriel'},...
    {'Sreiburg','Freiburg'},...
    {'Seiburg','Freiburg'},...
    {'Hallerm','Sitzung'},...
    {'Pardinische','Sardinische'},...
    {'Ausliesserung','Auslieferung'},...
    {'Ausließerung','Auslieferung'},...
    {'Standantrag','Randantrag'},...
    {'vergelegten','vorgelegten'},...
    {'Maadt','Waadt'},...
    {'hettischen','hessischen'},...
    {'Sandantrag','Randantrag'},...
    {'Bandesrath','Bundesrath'},...
    {'Antikel','Artikel'},...
    {'Maade','Waadt'},...
    {'Tharass','Tharasp'},...
    {'Pezung','Sizung'},...
    {'Sanama','Panama'},...
    {'präglichen','fraglichen'},...
    {'Kollegior','Pollegio'},...
    {'Pardinischen','Sardinischen'},...
    {'sondenische','sardinische'},...
    {'serdinische','sardinische'},...
    {'fardinische','sardinische'},...
    {'fardinischen','sardinischen'},...
    {'fordenischen','sardinischen'},...
    {'Fard.','Sard.'},...
    {'Sehefr','Septr.'},...
    {'Prälternen','Prellereien'},...
    {'Tennf','Gennf'},...
    {'Maran','Aarau'},...
    {'Karau','Aarau'},...
    {'Karan','Aarau'},...
    {'Darau','Aarau'},...
    {'Karbach','Marbach'},...
    {'Aargan','Aargau'},...
    {'Stargau','Aargau'},...
    {'Prattale','Pratteln'},...
    {'Schwytz','Schwyz'},...
    {'Aargari','Aargau'},...
    {'Heo-York','New-York'},...
    {'Cleo-Thork','New-York'},...
    {'Pleo-Thork','New-York'},...
    {'Kandleute','Landleute'},...
    {'Inzerich','Luzern'},...
    {'Barn','Bern'},...
    {'esterreich','Österreich'},...
    {'Kolldepartement','Zolldepartement'},...
    {'Gostdepartement','Postdepartement'},...
    {'Beirern','Bureau'},...
    {'Lustiz','Justiz'},...
    {'hössische','hessische'},...
    {'Anigier','Ringier'},...
    {'Kinderne','Kindern'},...
    {'Abaizina','Maizena'},...
    {'Solothember','Solothurn'},...
    {'Firmannhabers','Firmainhabers'},...
    {'Lisholz','Fürholz'},...
    {'Bazenhan','Bazenhaid'},...
    {'Tragenburger','Toggenburger'},...
    {'Bazenlaid','Bazenhaid'},...
    {'Javos','Davos'},...
    {'Postcominis','Postcommis'},...
    {'Departeinent','Departement'},...
    {'Beibeng','Freiburg'},...
    {'Industre','Industrie'},...
    {'Agant','Agent'},...
    {'Pischenien','Rio de Janeiro'},...
    {'Koloniere','rest: Kolonien'},...
    {'sventanadaverie','Vermögensangelegenheit'},...
    {'Graswinserfügungen','Präsidialverfügungen'},...
    {'Pasialverfügungen','Präsidialverfügungen'},...
    {'Sizuna','Sizung'},...
    {'dehartement','Departement'},...
    {'Schartement','Departement'},...
    {'separtement','Departement'},...
    {'goll-departement','Zoll Departement'},...
    {'Sindustrie','Industrie'},...
    {'Sidustrie','Industrie'},...
    {'Simson','Simplon'},...
    {'Hashington','Washington'},...
    {'Pezung','Sizung'},...
    {'Träsdt','Präsid'},...
    {'Richsc','Ruffy'},...
    {'Republikt','Republik'},...
    {'geschreckt','Geschenk'},...
    {'Tobegramm','Telegramm'},...
    {'Brendesrat','Bundesrat'},...
    {'Huttgart','Stuttgart'},...
    {'Eisenbalm','Eisenbahn'},...
    {'Saumsehen','Baumwesen'},...
    {'Kothisie','Rothsee'},...
    {'Thverdon','Yverdon'},...
    {'Thoerdon','Yverdon'},...
    {'Thverdonn','Yverdon'},...
    {'Thverdon','Yverdon'},...
    {'Obiken','Ebikon'},...
    {'Reuens','Renens'},...
    {'Sommersalerschuss','Sommerfahrplan'},...
    {'Niveankreuzung','Niveaukreuzung'},...
    {'Kufsch','Ruffy'},...
    {'Besp','Zemp'},...
    {'Lanzler','Kanzler'},...
    {'Heapel','Neapel'},...
    {'Luzernburg','Luxemburg'},...
    {'Sennsylvania','Pennsylvania'},...
    {'pacherliche','kaiserliche'},...
    {'Prasu','Präsid.'},...
    {'Schwytza','Schwytzer'},...
    {'Schwaz','Schweiz'},...
    {'Uriterstellung','Unterstellung'},...
    {'Urig','Ursy'},...
    {'Sustiz','Justiz'},...
    {'zürcharische','zürcherische'},...
    {'Aargan','Aargau'},...
    {'Kargan','Aargau'},...
    {'Hargan','Aargau'},...
    {'Stargau','Aargau'},...
    {'An penzell','Appenzell'},...
    {'Auberrhoden','Appenzell'},...
    {'Aeppenzell','Appenzell'},...
    {'Appengell','Appenzell'},...
    {'Inner Rhoden','Appenzell'},...
    {'Aphenzell','Appenzell'},...
    {'Appenzelluth','Appenzell'},...
    {'Bafel','Basel'},...
    {'Paisel','Basel'},...
    {'Badel','Basel'},...
    {'Berm,','Bern'},...
    {'Friborug','Fribourg'},...
    {'Friboing','Fribourg'},...
    {'Triburg','Fribourg'},...
    {'Fribour','Fribourg'},...
    {'Geef,','Genf'},...
    {'Glacus','Glarus'},...
    {'Garus','Glarus'},...
    {'Glacis','Glarus'},...
    {'Glaru','Glarus'},...
    {'Glarusz','Glarus'},...
    {'Alarus','Glarus'},...
    {'Blarus','Glarus'},...
    {'Clarus','Glarus'},...
    {'Glares','Glarus'},...
    {'Glarens','Glarus'},...
    {'Glariis','Glarus'},...
    {'Glar','Glarus'},...
    {'Graubunden','Graubünden'},...
    {'Traubünden','Graubünden'},...
    {'Traubunden','Graubünden'},...
    {'Fraubünden','Graubünden'},...
    {'Fraubunden','Graubünden'},...
    {'Graubenden','Graubünden'},...
    {'Grasbünden','Graubünden'},...
    {'Grasbunden','Graubünden'},...
    {'Chraubünden','Graubünden'},...
    {'Graubündten','Graubünden'},...
    {'Graubündent','Graubünden'},...
    {'Graubündern','Graubünden'},...
    {'Duzern','Luzern'},...
    {'Euzern','Luzern'},...
    {'euzern','Luzern'},...
    {'Leuzern','Luzern'},...
    {'Juzern','Luzern'},...
    {'Kuzern','Luzern'},...
    {'Cluzern','Luzern'},...
    {'Kuzern','Luzern'},...
    {'auzern','Luzern'},...
    {'Leizern','Luzern'},...
    {'Auzern','Luzern'},...
    {'Hluzern','Luzern'},...
    {'Lucern','Luzern'},...
    {'Lubern','Luzern'},...
    {'Luzerin','Luzern'},...
    {'Luzizern','Luzern'},...
    {'Luzerni','Luzern'},...
    {'Heuchatel','Neuchâtel'},...
    {'Neschätel','Neuchâtel'},...
    {'Neuchafel','Neuchâtel'},...
    {'Neschatel','Neuchâtel'},...
    {'Nachatel','Neuchâtel'},...
    {'Necenburg','Neuenburg'},...
    {'Heuenburg','Neuenburg'},...
    {'Venenburg','Neuenburg'},...
    {'Leuenburg','Neuenburg'},...
    {'Nebenburg','Neuenburg'},...
    {'Deuenburg','Neuenburg'},...
    {'Beuenburg','Neuenburg'},...
    {'Meuenburg','Neuenburg'},...
    {'Neuenberg','Neuenburg'},...
    {'idwalden','Nidwalden'},...
    {'Sidwalden','Nidwalden'},...
    {'Eidwalden','Nidwalden'},...
    {'Ridwalden','Nidwalden'},...
    {'Widwalden','Nidwalden'},...
    {'Eidwalden','Nidwalden'},...
    {'Abwalden','Obwalden'},...
    {'bwalden,','Obwalden'},...
    {'Schwyzl,','Schwyz'},...
    {'Schwytz','Schwyz'},...
    {'Schwyze','Schwyz'},...
    {'lchwytz','Schwyz'},...
    {'Ichwyz,','Schwyz'},...
    {'Polothurn','Solothurn'},...
    {'Golothurn','Solothurn'},...
    {'Tolothurn','Solothurn'},...
    {'Dolothurn','Solothurn'},...
    {'Colothurn','Solothurn'},...
    {'Jolothurn','Solothurn'},...
    {'Lolothurn','Solothurn'},...
    {'Solothurie','Solothurn'},...
    {'Solothurne','Solothurn'},...
    {'Solothan','Solothurn'},...
    {'Ct. Gallen','St. Gallen'},...
    {'wSr. Kellen','St. Gallen'},...
    {'Sr. Hallen','St. Gallen'},...
    {'B. Gallen,','St. Gallen'},...
    {'Sessin','Tessin'},...
    {'Dessin','Tessin'},...
    {'Fessin','Tessin'},...
    {'Pessin','Tessin'},...
    {'stessin','Tessin'},...
    {'Lessin','Tessin'},...
    {'Kessin','Tessin'},...
    {'Tassin','Tessin'},...
    {'Jessin','Tessin'},...
    {'dhurgau','Thurgau'},...
    {'Churgau','Thurgau'},...
    {'Bhurgau','Thurgau'},...
    {'Thaurgau','Thurgau'},...
    {'Thurgaui','Thurgau'},...
    {'Kurgau','Thurgau'},...
    {'Murgau','Thurgau'},...
    {'Thurgau','Thurgau'},...
    {'Nurgau','Thurgau'},...
    {'Thurgazu','Thurgau'},...
    {'Kri','Uri'},...
    {'Ari','Uri'},...
    {'Urii','Uri'},...
    {'Urig','Uri &'},...
    {'Maadt','Waadt'},...
    {'Maade','Waadt'},...
    {'Wandt','Waadt'},...
    {'Marack','Waadt'},...
    {'Waadtl','Waadt'},...
    {'Haadt','Waadt'},...
    {'Waailt','Waadt'},...
    {'Saadt','Waadt'},...
    {'Paadt','Waadt'},...
    {'Baadt','Waadt'},...
    {'Hallis','Wallis'},...
    {'Ballis','Wallis'},...
    {'Kallis','Wallis'},...
    {'Mallis','Wallis'},...
    {'Fürich','Zürich'},...
    {'Zurich','Zürich'},...
    {'Berich','Zürich'},...
    {'Rürich','Zürich'},...
    {'Bürich','Zürich'},...
    {'Dürich','Zürich'},...
    {'Mürich','Zürich'},...
    {'Türich','Zürich'},...
    {'Kürich','Zürich'},...
    {'hürich','Zürich'},...
    {'Würich','Zürich'},...
    {'pürich','Zürich'},...
    {'Zurice','Zürich'},...
    {'Züriche','Zürich'},...
    {'Zuriche','Zürich'},...
    };
nsar = length(sar);

% -----------------
% Read file list
% -----------------
% MAC
root = 'nlp/bar/data/';
% root = '/Volumes/NB74/bar/export_job_2126377/';
% root = '/Volumes/NB74/bar/test/';
% PC
% root = 'E:\bar\test\';

flist = dir([root,'**/*.xml']);
nlist = length(flist);

% delete any preexisting error log files
logUnreadable = [root,'log unreadable files.txt'];
status = isfile(logUnreadable);
if status == true
    delete(logUnreadable)
end


% -----------------
% Search and replace terms
% -----------------
% measure processing duration
t0 = tic;
% disp(datetime(now,'ConvertFrom','datenum')

% loop files
fileUnreadableNr = 0;
fileUnreadableId = struct();
fileUnreadableId(1).fname = '';

progressStep = floor(nlist/10);
progressIter = 0;
for klist = 1:nlist
    
    % skip non-transcription files
    if strcmp(flist(klist).name,'metadata.xml') || ...
            strcmp(flist(klist).name,'mets.xml')
        continue
    end
    
    % read file
    fname = flist(klist).name;
    fpath = [flist(klist).folder,filesep,fname];
    try
        txt = fileread(fpath);
    catch
        fileUnreadableNr = fileUnreadableNr + 1;

        % log unreadable file name
        fid = fopen(logUnreadable,'a','n','UTF-8');
        fwrite(fid, [fpath,newline]);
        fclose(fid);
        
        continue
    end

    % search and replace
    for ksar = 1:nsar
        
        % -----------------
        % Search criteria
        % -----------------
        % - whole word
        % - ignore case
        
        pat = ['\<',sar{ksar}{1},'\>'];
        rep = sar{ksar}{2};
        txt = regexprep(txt,pat,rep,'ignorecase');

    end
    
    % save file
    fid = fopen(fpath,'w','n','UTF-8');
    encoded_txt = unicode2native(txt, 'UTF-8');
    fwrite(fid, encoded_txt);
    fclose(fid);
    
    % display progress
    if mod(klist,progressStep) == 1
        fprintf(num2str(progressIter))
        progressIter = progressIter + 1;
    end
    
end
fprintf('0\n')


% -----------------
% Display results
% -----------------
disp(['Total files to upload: ',num2str(nlist)])
disp(['Files unreadable: ',num2str(fileUnreadableNr)])

% display processing duration
disp(datetime(now,'ConvertFrom','datenum'))
dt = toc(t0);
dt = datestr(seconds(dt),'HH:MM:SS');
dt = datevec(dt);
dt = [...
    num2str(dt(4)),'h ',...
    num2str(dt(5)),'m ',...
    num2str(dt(6)),'s'];
del = '';
if dt(6) == 0
    dt = ['less than ',dt];
end
msg = ['Processing duration was ',dt,'.'];
disp(msg)



